# Generated by Django 5.2.10 on 2026-03-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_module_profile', to='authentication.user'),
        ),
    ]
