# Generated by Django 5.2.10 on 2026-03-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_facultycourseassignment_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultycourseassignment',
            options={'verbose_name': 'Faculty Course Specialization', 'verbose_name_plural': 'Faculty Course Specializations'},
        ),
    ]
