# Generated by Django 5.2.10 on 2026-03-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_facultycourseassignment_options'),
        ('student', '0004_studentprofile_branch_studentprofile_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('branch', models.CharField(choices=[('Computer science engineering', 'Computer science engineering'), ('Artificial Intelligence and machine Learning', 'Artificial Intelligence and machine Learning'), ('electronics and communication', 'electronics and communication'), ('Data science', 'Data science'), ('Information technology', 'Information technology'), ('mechanical engineering', 'mechanical engineering'), ('Civil engineering', 'Civil engineering'), ('Robotics and Artificial Intelligence', 'Robotics and Artificial Intelligence'), ('Internet of things', 'Internet of things')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='student.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_assignments', to='faculty.facultyprofile')),
            ],
        ),
    ]
