# Generated by Django 6.0.3 on 2026-03-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
