# Generated by Django 5.2.10 on 2026-03-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_assignment_allow_submissions_assignment_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='allow_submissions',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='max_marks',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
    ]
