# Generated by Django 5.2.10 on 2026-03-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_sectioncoordinator'),
        ('student', '0008_feemonitoringlog_feeintervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment_url',
            field=models.URLField(blank=True, help_text='Link to supporting materials (e.g. Google Drive, PDF)', null=True),
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Submission notes or link to work')),
                ('attachment_url', models.URLField(blank=True, help_text='Link to submitted file', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='faculty.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='student.studentprofile')),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
