# Generated by Django 5.2.10 on 2026-03-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_assignment_attachment_url_assignmentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='attachment_url',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='attachment_url',
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload instructions/notes in PDF or Word format', null=True, upload_to='assignments/materials/'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload your work in PDF or Word format', null=True, upload_to='assignments/submissions/'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='content',
            field=models.TextField(blank=True, help_text='Submission notes', null=True),
        ),
    ]
