# Generated by Django 4.2.16 on 2026-03-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_feemonitoringlog_feeintervention'),
        ('faculty', '0011_remove_assignment_attachment_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='due_date',
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date & Time'),
        ),
        migrations.CreateModel(
            name='AssignmentReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('50', '50% Duration'), ('75', '75% Duration'), ('90', '90% Duration'), ('day_morning', 'Submission Day Morning'), ('day_evening', 'Submission Day Evening'), ('final', '3 Hours Before Deadline')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='faculty.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_reminders', to='student.studentprofile')),
            ],
            options={
                'unique_together': {('assignment', 'student', 'reminder_type')},
            },
        ),
    ]
