# Generated by Django 5.2.12 on 2026-03-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_remove_assignment_due_date_assignment_due_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_mode',
            field=models.CharField(choices=[('online', 'Online (via Portal)'), ('offline', 'Offline (Physical Submission)')], default='online', max_length=10, verbose_name='Submission Mode'),
        ),
    ]
