# Generated by Django 5.2.10 on 2026-03-31 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_alter_assignment_attachment_and_more'),
        ('student', '0008_feemonitoringlog_feeintervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload instructions/notes in PDF or Word format', null=True, upload_to='assignments/materials/'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload your work in PDF or Word format', null=True, upload_to='assignments/submissions/'),
        ),
        migrations.CreateModel(
            name='SubjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('branch', models.CharField(choices=[('Computer science engineering', 'Computer science engineering'), ('Artificial Intelligence and machine Learning', 'Artificial Intelligence and machine Learning'), ('electronics and communication', 'electronics and communication'), ('Data science', 'Data science'), ('Information technology', 'Information technology'), ('mechanical engineering', 'mechanical engineering'), ('Civil engineering', 'Civil engineering'), ('Robotics and Artificial Intelligence', 'Robotics and Artificial Intelligence'), ('Internet of things', 'Internet of things')], max_length=100)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.FileField(help_text='Upload notes in PDF, DOCX, or PPT format', upload_to='notes/materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_notes', to='student.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_notes', to='faculty.facultyprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='StudyNote',
        ),
    ]
