# Generated by Django 4.2.16 on 2026-03-31 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_alter_assignment_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAssignmentReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_stage', models.CharField(choices=[('50', '50% Milestone'), ('75', '75% Milestone'), ('90', '90% Milestone'), ('final', 'Final Deadline Report')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_report_logs', to='faculty.assignment')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_reports', to='faculty.facultyprofile')),
            ],
            options={
                'unique_together': {('assignment', 'faculty', 'report_stage')},
            },
        ),
    ]
