# Generated by Django 5.2.10 on 2026-03-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentprofile_branch_studentprofile_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
