# Generated by Django 6.0.1 on 2026-03-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentprofile_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateTimeField(auto_now_add=True)),
                ('students_analyzed', models.IntegerField(default=0)),
                ('students_at_risk', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('reports_generated', models.IntegerField(default=0)),
                ('summary_insight', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='attendance_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10),
        ),
        migrations.CreateModel(
            name='AttendanceIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_attendance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notification_sent', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='student.attendancemonitoringlog')),
            ],
        ),
    ]
