# Generated by Django 5.2.10 on 2026-03-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_attendancemonitoringlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
