# Generated by Django 5.2.10 on 2026-03-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentprofile_parent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeMonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateTimeField(auto_now_add=True)),
                ('students_analyzed', models.IntegerField(default=0)),
                ('overdue_students', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('reports_generated', models.IntegerField(default=0)),
                ('summary_insight', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_overdue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notification_sent', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='student.feemonitoringlog')),
            ],
        ),
    ]
